permaweb/aos

src/register.js

This PR allows users to start new processes with custom tags on aos. It can be used like this:
```sh
aos chatroom --tag-name Chat-Theme --tag-value Dark --tag-name Chat-Name --tag-value Mychat  
```
The command above will produce an aos process with the following tags:
```ts
{
...
{ name: "Chat-Theme", value: "Dark" },
{ name: "Chat-Name", value: "Mychat" }
...
}
```
The feature can be useful for processes that use `ao.env.Process.Tags` as environment variables.

Custom tag support for starting processes

---

src/commands/load.js

This PR allows users to `.load` a file that is not in the workspace that aos runs in. For instance:
```
.load /Users/marton/Desktop/Projects/my-project/test.lua
```

Support absolute paths for ".load"

---

process/utils.lua

This PR fixes the `keys()` and `values()` function in utils. My old implementation incorrectly used the `map()` function, which only works on arrays, but these two functions are specifically made for non-array tables.
(I apologise for my mistake)

Hotfix keys/values function in utils

---

blueprints/token.lua

```
if (msg.Tags.Target and Balances[msg.Tags.Target]) then
bal = Balances[msg.Tags.Target]
elseif Balances[msg.From] then
bal = Balances[msg.From]
end
```
Above is the code for previous handler where we are taking the value of `Target` tag to fetch the balance however, `Target` tag will always contains the pid for the `token blueprint` as it is a defined tag for `Send` function. Hence, I changed it to `Recipient` to check balance which follows the transfer terminologies.

fix: check balance handler

---

process/handlers-utils.lua
process/handlers-utils.md

This PR adds 2 new utility functions for handlers:
- `continue()`
Allows wrapping pattern matching functions (such as the built in `hasMatchingTag()`) so that instead of "breaking" at the end of the handler's execution, they allow the process to continue executing other matching handlers.
```lua
-- useful for built in pattern matching functions
Handlers.add(
"stake",
-- this handler will stake tokens, then it will "continue"
Handlers.utils.continue(Handlers.utils.hasMatchingTag("Action", "Stake")),
staking.stake
)
```
- `hasMatchingTagOf()`
Allows matching multiple values for a tag.
```lua
-- useful for finalizers
Handlers.add(
"finalizer",
-- this handler will finalize results for both the "stake" and "unstake" actions
Handlers.utils.hasMatchingTagOf("Action", { "Stake", "Unstake" }), …
```

New handler utility functions

---

blueprints/arena.lua

This code seems not correct, which divide by zero first.

fix(blueprints): remove dump code in arena.lua

---

process/handlers-utils.lua

Currently the implementation returns wrong results if the matching tag value is not the first one in the loop. This is caused by the differently formatted result from the `hasMatchingTag()` pattern.

Fix handler utils `hasMatchingTagOf()` pattern

---

blueprints/token.lua

Fixes declaration of `Ticker` that was checking for value `'Points'` and setting it to `'PNTS'`

Typo in `Ticker` declaration

---

blueprints/token.lua

After the conversation at #214, I have gone ahead and created a basic implementation for forwarded tags. 
This forwards any tags coming from a transfer that begins with the prefix `X-` with the `Credit-Notice` and `Debit-Notice` messages. It does not forward the tags for transfer error messages, I'm happy to add it there as well. 
Some points that are worth noting for the future (all mentioned in the conversations had around this feature, so this is just a summary):
- `X-` is used as a prefix after the customary `X-` prefix for http headers (indicating that the header is of a non-standard name). Generally ao (and Arweave) tries to follow the http header syntax
- Forwarded tags are not encoded in a single tag as a JSON string, because:
- JSON stringy are hard to query via GraphQL
- Tags …

Forwarded tags support

---

src/commands/load.js
src/index.js
src/services/errors.js
src/services/loading-files.js

This PR adds error parsing and improved error messages. It parses the origin of the error and displays it.
Before:
After:
It can also handle errors from loaded projects and point to the original (local) file where the error occurred.

Better error messages

---

src/register.js

This PR fixes an issue where if you have a number as a `--tag-value` when spawning a new aos process, it errors, because tags can only be strings. The fix converts all inputs to strings.

Fix number inputs for spawn tags

---

src/services/get-pkg.js

reproduced the error. I think this may fix it. 
please double check!
fixes #200

bug(get-pkg) aos fails if launched on separate drive.

---

src/services/errors.js

Without this patch the AOS client crashes completely when the process gives it a response with no error content. This PR makes it instead return a generic error message with a `0` line number.

fix: Don't crash the AOS CLI when an unknown error occurs on the process.

---

process/handlers.lua
process/process.lua

This commit adds support for:
- Handlers.once: A method of adding a single-run handler that is removed after exection.
- Optional MaxRuns argument for each handler, letting you choose the number of runs before it removes itself. Default is infinite.
- More expressive and easy to use matches. As well as functions, handlers now supports:
-> Strings as match, checking against the Action tag.
-> 'MessageMatchSpecs': Partially described messages. In this mode, each tag given in the 'spec' is checked against the value in the message. It allows you to:
1. Wildcard: Is the tag given at all?
2. Function: Run a function against the tag value (optional second argument is the full message)
3. String: Exact match
4. String: Lua matching syntax

 feat: add support for more expressive handlers.

---

process/process.lua
process/test/handlers.test.js

Closes #276 
This PR allows users to access the most recent ```msg.Timestamp``` via ```os.time()``` for a more intuitive user experience.
Added a single line to the ```process.handle``` method ```os.time = function () return msg.Timestamp end``` which overides the os.time() method to return msg.Timestamp.
Added a test to handlers.test.js to confirm functionality.

feat(aos-process): os.time should return the msg.Timestamp #276

---

src/services/connect.js

Closes #275
This PR is to address an issue with messages printing out of order in the aos cli.
The solution was to sort the `edges` returned from `graphql` by the `ordinate` **_encoded_** inside of the **_base64 decoded_** `cursor`.
Was going to sort by the `timestamp` **_encoded_** inside the `cursor` but the timestamps seem to not be a direct indicator of message order. Most likely due to the asynchronous nature of the CU?
Added a single line of code to sort the edges inside the `checkLive` function in `services/connect.js`.
```js
// Sort the edges by ordinate value to ensure they are printed in the correct order.
edges = edges.sort((a, b) => JSON.parse(atob(a.cursor)).ordinate - JSON.parse(atob(b.cursor)).ordinate);
```

fix(aos-cli): live feed message sorting #275

---

.gitignore
src/services/errors.js
src/services/loading-files.js

Unicode for NBSP is not safe for all environments, its better to replace it with space.
Also ignoring .vscode would be helpful, as there is no formatting within the repo & may interfere with format-on-save and such things.

gitignore `.vscode`, replace `U+00a0` with space

---

blueprints/token.lua

Fixes https://github.com/permaweb/aos/issues/288
The current implementation errors on `bint` inputs. Should be using `bint.tonumber(a)` instead of the native `tonumber(a)`

Fix utils.toNumber() in token.lua

---

src/index.js
src/services/history-service.js

Currently the input history for a session is saved, where a user can us the up arrow key to cycle through previous inputs. 
This PR is to save the 100 most recent history items in order to give access to them after the session is closed and restarted.

feat(aos): save input history after exiting a session #329

---

src/index.js

Loading a lua file with modules using the --load flag will have the modules appended as string to the end of the lua file.  
Example:
Updating the `handleLoadArgs` function to only map the lua code fixes the problem

fix: error when loading lua file with modules using the --load flag

---

extensions/weavedrive/client/main.lua
extensions/weavedrive/src/index.js
extensions/weavedrive/test/index.test.js

Before, if GQL query returned no results (invalid tx), then would throw error (node is undefined). Now, return 0.

fix(weavedrive): if no gql results, return 0

---

process/handlers.lua

If nil is passed as index to table.remove, it removes the last element. Now, only call if idx exists.
https://www.lua.org/pil/19.2.html

fix(aos): only remove handler if name matches

---

process/handlers-utils.lua
process/handlers-utils.md

Right now there is no way to easily allow continuing execution if you use pattern specs in aos. Until now, the `Handlers.utils.continue()` shortcut function only supported pattern matching functions as input, this update extends this to the following:
```lua
Handlers.add(
"test-action-that-continues",
Handlers.utils.continue({ Action = "Some-Action" }),
some.actionHandler
)
```

Support pattern specs in `Handlers.utils.continue()`

---

.github/workflows/weavedrive.yml
extensions/weavedrive/package-lock.json
extensions/weavedrive/package.json
extensions/weavedrive/src/index.js
extensions/weavedrive/test/index.test.js

This PR fixes an issue in WeaveDrive, where a non-existent arweavejs client was being used to call an arweave gateway. The rest of the impl uses an internal api built around `fetch`, so I simply swapped the use arweavejs to using that api as well.
This PR also fixes malformed graphql queries that would fail, if made to an arweave gateway.
This PR also fixes a bug where module tags were being checked instead of process tags, when determining the `Availablity-Type`
Finally, I added tests to assert the correctness of loading txs in `Availability-Types` `Assignments` and `Individual`
> the code changes are small -- the largest diff is the tests, which were previously unimplemented.

fix(weavedrive): use fetch in lieu of arweave js client to make graphql calls. Fix graphql operations.

---

extensions/weavedrive/src/index.js
extensions/weavedrive/test/index.test.js

fix(weavedrive): store headers as utf8 encoded

---

process/utils.lua

fix(aos): matchesspec does not work with from-process #337

---

blueprints/chatroom.lua

Adding an Action Tag to the Broadcasted message could help filter chatroom message from all the other incoming messages. This filtered output could be stored in a separate variable or help in creating a frontend listener just for chats while ensuring the chatroom blueprint does not need a separate process

Add Action Tag to broadcasted messages in Chatroom Blueprint

---

src/services/version.js
test/services/version.test.js

I was receiving this error earlier today and couldn't connect to my process:
I found the issue was around the response code returned from fetching from `UPDATE_URL` (value is `https://get_ao.g8way.io`) for an update. The response code was `502`.
Although this PR doesn't address every edge case, it addresses the one I experienced earlier today. This PR introduces the following:
- Returns `{ available: false }` if fetching from update URL returns a 5xx status code
- Adds tests to ensure 404 and 5xx status codes return `{ available: false }`
- When `process.env.DEBUG` is truthy, a warning message will be shown for fetches that result in 5xx status codes. For example:

fix(services/version): prevent checkForUpdate() 5xx response codes from stopping connection

---

src/services/loading-files.js

When loading multiple files, module names with "-" in them cause syntax errors. "-" is not also replaced with "_".

Fix `-` breaking loaded projects

---

README.md
process/docs/modules/ao.html

docs: fix typos

---

README.md

The README doesn't make it clear that we are able to connect to existing processes by process ID. I added a quick explanation to the README in this PR.
This is useful information for those who deployed their AO process with tools other than AOS, such as ao-deploy.

README: Add instructions for connecting to existing process ID

---

.gitignore
process/process.lua
process/test/normalized-message.test.js

Introduces enhanced message normalization to ensure consistent key and tag name formatting across the AO network by converting them to title case.
- **Added `normalizeMsg()` function** that normalizes message keys and tag names to title case
- Handles dashes and underscores (e.g., `data-protocol` → `Data-Protocol`)
- Replaces `ao.normalize(msg)` in main handler while preserving existing functionality
- **Added tests for normalized message keys** (`process/test/normalized-message.test.js`)

Normalize Incoming Message Tags
