permaweb/aos

process/utils.lua, process/utils.test.js
A little reuse. Also updated the `utils.test.js` by capitalizing inputs and outputs and added a test case for `utils.filter`. Finally made the error feedback clearer
=> refactor(process): implement utils.map and utils.filter using utils.reduce

src/index.js, src/services/wallets.js
=> feat: allow user to specify a wallet to create or connect to process with

process/utils.lua
- Allow using the current element's key in the map function of `utils.map()`
- Support variable number of arguments in `utils.compose()`
- Add `utils.reverse()`
- Add `utils.includes()`
- Add `utils.keys()`
- Add `utils.values()`
=> Array mutation additions

package.json, src/index.js, src/services/version.js, yarn.lock
This PR adds a self updater, that fetches the latest aos tarball on startup, checks if its version is newer than the current aos instance's, asks the user if they would like to update and finally overwrites the current aos files with the latest ones.
=> AOS updater

blueprints/credUtils.lua
CRED.balace shows balance
CRED.update updates balance
CRED.process prints PID of CRED
CRED.send("hash", amount) sends CRED
=> feat: Added credUtils lua file to blueprints

src/services/connect.js, src/services/dev.js, src/services/gql.js
The most important this here is passing `GATEWAY_URL` down into `aoconnect`, otherwise you cannot control which gateway it uses.
=> feat(env-vars): better handling and pass down into `aoconnect`

blueprints/token.lua
Related: https://github.com/permaweb/ao/pull/599
=> Add Total-Supply handler to token.lua blueprint

README.md, blueprints/token.lua, package.json
Token lua script was over-writing `Name, Ticker, and Denomination` when updating, the token lua script should not over-write Name, Ticker, and Denomination when updating....
=> fix: update token and bump version

extensions/weavedrive/README.md, extensions/weavedrive/build.js, extensions/weavedrive/package.json, extensions/weavedrive/src/index.js
AOS should support extensions
The first extension is the first one is weaveDrive
=> add weavedrive extension

blueprints/token.lua
Rather than computing it on the fly, we should calculate it on each mint/burn for better performance.
=> Improve TotalSupply calculation

README.md, package-lock.json, src/index.js, src/services/connect.js, src/services/help.js, yarn.lock
Added `--gateway-url`, `--cu-url`, `--mu-url` flags to run **`aos`** on those endpoints without changing env vars
=> feat: gateway, cu, mu url flags

blueprints/apm.lua
This PR is to add the experimental ao package manager client, from BetterIDEA
=> feat: added apm client blueprint

src/index.js
Fix PR #254,
The env var set for MU wasn't the good one
=> fix: mu env var

blueprints/arns.lua, blueprints/token.lua
This PR has the following changes:
- Expected solution for issue #269 
- Update in the pid of 0rbit process in arns.lua file
Apologies, for creating the same PR for 2 different set of commits
=> Resolve #269 and update 0rbit pid

blueprints/apm.lua
The client now checks for latest version from the apm registry process and notifies the user to update their apm through `APM.update()`
=> update: apm.lua blueprint

process/process.lua, src/evaluate.js, src/index.js, src/services/connect.js, src/services/help.js, src/services/splash.js, src/services/version.js
This PR implements a number of 'low hanging fruit' improvements for the AOS DevX. Including:
- A more informative and useful default `Prompt()`
- Clearer help messages for the AOS client
- Normalized capitalization of nouns in the AOS client
- Tidier message processing messages
- Removed unnecessary newline prints during DEBUG=1 timing statements
=> feat: Quality of Life Improvements and Spring Cleaning

blueprints/apm.lua
Updated the APM client blueprint to use the assignable whitelist
=> update: assignable package installer

process/ao.lua, process/handlers-utils.lua, process/handlers.lua, process/process.lua, process/test/handlers.test.js
Latest adjustments to AOS 2.
> if only two arguments added then
- handlers.add("Balance", function (msg) msg.reply({ Data = Balances[msg.Recipient or msg.From]}) end)
- added ao.lua to aos process
=> chore: mv ao.lua to aos and make handlers arguments dynamics

blueprints/apm.lua
Update apm client blueprint to include:
- dependency support
- publisher provided warnings
- Shifted publishing to use [apm-cli-tool](https://www.npmjs.com/package/apm-tool)
- Renamed the new package manager namespace from 'APM' to 'apm'
=> Update apm.lua to v2.0.0

extensions/weavedrive/package.json, process/process.lua, src/commands/os.js
=> updated weavedrive

blueprints/apm.lua
Loading the APM blueprint now installs the latest apm client version from the registry.
This is a newly spawned process which installs the latest version of apm instead of having to install the old one and then update it
=> Update APM blueprint

src/services/errors.js, src/services/loading-files.js
Previous PR (#371) missed a few edge cases that have popped up in the weeks since. This PR is a more indepth approach to finding the error Origin.
=> fix(aos): fix error lines base cases, loading

hyper/bundle.js, hyper/spec/string-ext_spec.lua, hyper/src/string-ext.lua
The string.gmatch function is a powerful tool for text processing and data extraction that many developers rely on. Adding this functionality to HyperAOS ensures feature parity with legacy systems and provide users with a familiar way to work with strings.
- Implement string.gmatch: Adds the Lua string.gmatch function to the HyperAOS environment
- Pattern Matching Engine: Utilizes an efficient pattern matching engine that supports both simple and complex patterns
- Performance: Optimizes for speed, especially when processing large strings or complex patterns
- Security: Ensures proper sanitization of user-provided patterns to prevent injection vulnerabilities
- Testing: Comprehensive unit tests to verify functionality and edge cases
```
hyper % busted …
```
=> (FOR-133) Add support for Lua's string.gmatch function to the HyperAOS environment

hyper/spec/ao_spec.lua, hyper/spec/handlers_spec.lua, hyper/spec/json_spec.lua, hyper/spec/main_simple_spec.lua, hyper/spec/main_spec.lua, hyper/spec/process_spec.lua, hyper/src/main.lua
Added specs for core components of hyper aos
=> chore(hyper): add specs to cover main, ao, and more

blueprints/token.lua
=> Update token.lua blueprint
